language: csharp
solution: solution-name.sln
install:
  - nuget restore LeetCode.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release LeetCode.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./LeetCodeTests/bin/Release/LeetCode.Tests.dll
